### ISSUE TITLE
Object rest spread not supported

### ISSUE THREAD

**Issue by cayasso** [WebReflection/i18n-utils#2]
Hey great library, I am about to implement translation in one of my projects (react) and found this as a simple solution.
I am getting `Unexpected token ...`, This is related to `esprima` that doesn't support this yet until next major version [5.0](https://github.com/jquery/esprima/projects/2) and the `tolerant` option doesn't work in this case. Any quick fix for this? maybe use another parser `babylon` or `acorn` that support `object rest spread` via plugins or even better a small tagged template expression parser :-) ?

**Comment by WebReflection** [comment]
small tagged template expression parser would not be enough.

this project retrieves all template literals across all required/imported files which means it needs also require/import logic in place.

I wish esprima tolerate was more relaxed ... anyway, babylon seems to have all quirks in place but there's no way to intercept tokens while it's parsing, which is why I'm using esprima and its delegate functionality.

The issue wouldn't be in this project only neither, 'cause I am using esprima in [ascjs](https://github.com/WebReflection/ascjs) too which is responsible for simplifying parsing in here as well so ... whatever change you need here, it should land first in `ascjs` and then in `asbundle` and then in here.

I wonder if using esprima 5 right away would be sufficient though ... even if I'm looking for a long-term solution (but with syntax that keep changing I'm not sure if I'll ever pick the right one)

**Comment by WebReflection** [comment]
Current version `0.3` is based on babylon and it has all possible plugins enabled.

I hope this works for you now.

Regards

**Comment by cayasso** [comment]
Man you are awesome!!! definitely work for me and I am sure it will for others. I will be using it in my project https://spry.cr
So thank you!
